// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuiOIMUckzpwynQVjHjYoUJxgd2sJB_vc',
    appId: '1:114448980691:web:f25c87ebe49454a55e1226',
    messagingSenderId: '114448980691',
    projectId: 'krushimart-efba6',
    authDomain: 'krushimart-efba6.firebaseapp.com',
    storageBucket: 'krushimart-efba6.firebasestorage.app',
    measurementId: 'G-5KEEYRK5YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaymr1-2f9ppy5DwPoZ2jK7udZVnNNWog',
    appId: '1:114448980691:android:21ef61ecee197d9a5e1226',
    messagingSenderId: '114448980691',
    projectId: 'krushimart-efba6',
    storageBucket: 'krushimart-efba6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu-IW9YZEnwytKunHo3MR5f0_zz84y0uY',
    appId: '1:114448980691:ios:402c16b24de1ddcb5e1226',
    messagingSenderId: '114448980691',
    projectId: 'krushimart-efba6',
    storageBucket: 'krushimart-efba6.firebasestorage.app',
    iosBundleId: 'com.krushimart.krushimart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu-IW9YZEnwytKunHo3MR5f0_zz84y0uY',
    appId: '1:114448980691:ios:402c16b24de1ddcb5e1226',
    messagingSenderId: '114448980691',
    projectId: 'krushimart-efba6',
    storageBucket: 'krushimart-efba6.firebasestorage.app',
    iosBundleId: 'com.krushimart.krushimart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuiOIMUckzpwynQVjHjYoUJxgd2sJB_vc',
    appId: '1:114448980691:web:29d98395dc016f8b5e1226',
    messagingSenderId: '114448980691',
    projectId: 'krushimart-efba6',
    authDomain: 'krushimart-efba6.firebaseapp.com',
    storageBucket: 'krushimart-efba6.firebasestorage.app',
    measurementId: 'G-2Q0YV6ZJ4C',
  );

}